apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: common-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: sakethmirchi/event-driven-ecommerce/order-service:latest
        ports:
        - containerPort: 3000
