apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: common-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: sakethmirchi/event-driven-ecommerce/auth-service:latest
        ports:
        - containerPort: 3000
