apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: common-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service
        image: sakethmirchi/event-driven-ecommerce/payments-service:latest
        ports:
        - containerPort: 3000
